### ISSUE TITLE
Provide stubs for implementing a SmellsDetector 

### ISSUE THREAD

**Issue by faloi** [mumuki/mumukit#14]
A SmellsDetector is a component that, given:
- a set of inspections (aka the smells, provided by each runner)
- all the possible bindings for a source code (provided by each runner)
 
it can run all the inspections against each binding and report the failing ones.  

(https://github.com/mumuki/mumuki-hspec-server/blob/master/src/SmellsDetectorRunner.hs can be used as inspiration)

**Comment by flbulgarelli** [comment]
Solved with #30
