### ISSUE TITLE
Run tests inside a sandboxed environment

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumukit#3]
For security reasons, although we are limiting process memory and CPU time, and we are able to validate requests, it is very important to run tests inside a sandboxes environment that prevents accessing the actual file system and network. 

<del>Regarding FS, we should run tests inside chroot</del>

**Comment by flbulgarelli** [comment]
After some investigation, this is not that easy. It requires root permissions, and it is not a true secure sandbox.

**Comment by flbulgarelli** [comment]
Other options are:
* mocking FS/network libraries at programming language level. The problem with this is that in some languages it is not that easy, or not that secure. And it is not a secure solution always.
* Using docker sandboxes. It may be an overhead to create a container for each request, but perhaps we could have a pool of containers. 
* Creating our own sandboxing solution, like Valgrind

**Comment by flbulgarelli** [comment]
Here are some links:

* https://github.com/github/hoosegow
* http://stackoverflow.com/questions/29581005/how-to-run-a-pool-of-docker-containers-on-a-single-host-preserving-their-ip-addr
* http://stackoverflow.com/questions/1656227/how-does-valgrind-work/1656236#1656236
* https://www.npmjs.com/package/docker-pool

**Comment by flbulgarelli** [comment]
@faloi @mgarciaisaia

**Comment by mgarciaisaia** [comment]
I'd start by giving hoosegow a chance. It promises to be *the* thing we need.

If it ever gets to be a performance issue, we can see if it's worth implementing any of the other approaches - but this should be OK for a while, provided it works.

**Comment by faloi** [comment]
I agree with @mgarciaisaia, hoosegow seems nice. Let's give it a try.

**Comment by flbulgarelli** [comment]
I end up building a custom solution based on docker api, since I wanted to run any kind of code, not just ruby.
