### ISSUE TITLE
Servers can't access tempfiles from docker-machine

### ISSUE THREAD

**Issue by mgarciaisaia** [mumuki/mumukit#31]
On non-Linux platforms, you run Docker inside a Linux VM using `docker-machine`.

For enabling the container to see a volume, `docker-machine` has to share your host's (Windows or OS X) directory with the VM, and then set the volume link as it does in native Linux. Currently, there's a limitation by which only the users' directory is shared (the equivalent of `/home`). From [the docs](https://docs.docker.com/engine/userguide/containers/dockervolumes/#mount-a-host-directory-as-a-data-volume) (emphasis mine):

> If you are using Docker Machine on Mac or Windows, your Docker daemon has only limited access to your OS X or Windows filesystem. Docker Machine tries to auto-share your `/Users` (OS X) or `C:\Users` (Windows) directory. So, you can mount files or directories on OS X using.
> 
> ```
> docker run -v /Users/<path>:/<container path> ...
> ```
> 
> On Windows, mount directories using:
> 
> ```
> docker run -v /c/Users/<path>:/<container path> ...`
> ```
> 
> All other paths come from your virtual machine’s filesystem, **so if you want to make some other host folder available for sharing, you need to do additional work**. In the case of VirtualBox you need to make the host folder available as a shared folder in VirtualBox. Then, you can mount it using the Docker -v flag.

As [Mumukit creates temporary files](https://github.com/mumuki/mumukit/blob/ef9f5913721a666ebef68efb97b2241e5841c6e9/lib/mumukit/with_tempfile.rb#L6) in the OS' [...wait for it...] temporary directory, that's _outside_ the host-VM shared directories, so the server can't access the files. TL;DR - every spec fails.

Instructing `docker-machine` to share the temp directory with the Linux VM isn't straightforward - if doable at all.

What we _could_ do is to create the tempfile in a different directory, inside the user's home. The simplest thing to do is replace that line with `Tempfile.new(['mumuki.compile', tempfile_extension], Dir.home)` to create the tempfile within the user's home directory. For correctness sake, we could do that only when running in isolated environments. I don't think we could/should check for Windows/OSX/`docker-machine`.

The tempfile's supposed to get deleted anyway.

Does it make sense?

**Comment by flbulgarelli** [comment]
@aguspina ?

**Comment by flbulgarelli** [comment]
Since Docker has now first-class Mac support - https://blog.docker.com/2016/03/docker-for-mac-windows-beta - and Docker Machine is no longer required, this is no more an issue
