### ISSUE TITLE
Runner metadata should present spec structure

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumukit#59]

**Comment by julian-berbel** [comment]
- [ ] ruby
- [ ] java
- [ ] js
- [ ] gobstones
- [ ] haskell
- [ ] prolog
- [ ] python
- [ ] others

**Comment by flbulgarelli** [comment]
Do we need to modify mumukit bridge so that bibliotheca can consume this information? Or does it work as-is?

**Comment by flbulgarelli** [comment]
Ok, it does. See https://github.com/mumuki/mumukit-bridge/issues/8#event-1366199207
